language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install -e .[test]
script:
    - python setup.py -q test -q
notifications:
    email: false
