language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy-5.6.0
    - pypy3.3-5.5-alpha
include:
    matrix:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install -e .[test]
script:
    - python setup.py -q test -q
notifications:
    email: false
